05 template
js-tasks-ru/htmlcss-20211125_nxashiev pull request #10
Opened 2021-12-09 10:39 UTC by Khashiev

2021-12-09 10:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-13 15:17 UTC, GSemikozov requested changes

2021-12-13 15:17 UTC, GSemikozov commented on components/card/card.css
> +.card_aside {
это не карточка, а меню .aside / .side-nav

2021-12-13 15:17 UTC, GSemikozov commented on components/card/card.css
> +.card_section {
а это блок для описания компонента, например .component-description или как-тот так

2021-12-16 09:08 UTC, GSemikozov requested changes

2021-12-16 09:08 UTC, GSemikozov commented on components/card/card.css
> +.side-nav {
по-прежнему описываем одни компоненты в других - это ошибка)
если side-nav и component-description - это самостоятельные блоки, то их надо соответствующим образом и оформить

2021-12-17 19:58 UTC, Khashiev commented on components/card/card.css
> +.side-nav {
а как это сделать не создавая новый компонент, где их стили писать? pages/template.css?

2021-12-17 20:49 UTC, GSemikozov commented on components/card/card.css
> +.side-nav {
side-nav и component-description - просто другие компоненты, стили для них можно складывать в папке components.
главное правильно при создании компонентов - в файле компонента могут быть описаны стили которые касаются только этого компонента

2021-12-18 19:15 UTC, GSemikozov approved these changes

2021-12-18 19:15 UTC, merged