solution for 05-tooltip
js-tasks-ru/htmlcss-20211125_nxashiev pull request #12
Opened 2021-12-11 09:18 UTC by Khashiev

2021-12-11 09:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-13 15:19 UTC, GSemikozov requested changes

2021-12-13 15:19 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body {
вспомогательные стили для выравнивания тултипа на странице - примере компонента? уносим в тег style самого хтмл файла

2021-12-16 09:10 UTC, GSemikozov approved these changes

2021-12-16 09:11 UTC, merged