solution for 05-modal
js-tasks-ru/htmlcss-20211125_nxashiev pull request #13
Opened 2021-12-11 12:26 UTC by Khashiev

2021-12-11 12:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-13 15:20 UTC, GSemikozov requested changes

2021-12-13 15:20 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: fixed;
второй раз уже не обязательно - можно через absolute

2021-12-14 09:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-14 09:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-14 09:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-14 10:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-14 11:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-16 09:11 UTC, GSemikozov submitted a review, later dismissed

2021-12-16 09:11 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2021-12-16 14:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-16 14:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-16 20:35 UTC, GSemikozov approved these changes

2021-12-16 20:35 UTC, merged