solution for 07-toggler
js-tasks-ru/htmlcss-20211125_nxashiev pull request #19
Opened 2021-12-17 20:03 UTC by Khashiev

2021-12-17 20:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-17 20:53 UTC, GSemikozov requested changes

2021-12-17 20:53 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +  color: #495057;
заберем из переменных

2021-12-18 11:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-18 11:24 UTC, Khashiev commented on 07-lection5/03-toggler/toggler.css
> +  color: #495057;
прописал color через var

2021-12-18 11:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-18 12:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-18 19:15 UTC, GSemikozov approved these changes

2021-12-18 19:15 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2021-12-18 19:19 UTC, GSemikozov approved these changes

2021-12-18 19:19 UTC, merged