07 input
js-tasks-ru/htmlcss-20211125_nxashiev pull request #20
Opened 2021-12-18 16:34 UTC by Khashiev

2021-12-18 16:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-18 19:19 UTC, GSemikozov requested changes

2021-12-18 19:19 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.label {
название блока советую все-таки переименовать, например, в .input или .custom-input - тогда все внутренние элементы будут иметь знакомые и привычные семантические обозначения

2021-12-18 19:19 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  border: 1px solid var(--red);
здесь и в других модификаторах можно менять толко border-color

2021-12-18 19:19 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  outline: 0;
можно указать сразу на input

2021-12-18 19:19 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.label__input::placeholder {
по идее здесь отличие от основного текста толко в цвете

2021-12-19 13:27 UTC, Khashiev commented on 07-lection5/04-input/input.css
> +.label {
переписал все через custom-input

2021-12-19 13:28 UTC, Khashiev commented on 07-lection5/04-input/input.css
> +  border: 1px solid var(--red);
исправил

2021-12-19 13:28 UTC, Khashiev commented on 07-lection5/04-input/input.css
> +.label__input::placeholder {
удалил лишнее

2021-12-19 13:29 UTC, Khashiev commented on 07-lection5/04-input/input.css
> +  outline: 0;
перенес в custom-input__input

2021-12-19 13:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-19 19:02 UTC, GSemikozov requested changes

2021-12-19 19:02 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <svg class="custom-input__icon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
при позиционировании иконки через абсолют тут еще придется и высоту тайтла учитывать - чтобы привязываться лишь к размерам инпута, советую инпут и иконку завернуть в какой-нибудь врапппер

2021-12-19 19:04 UTC, Khashiev commented on 07-lection5/04-input/index.html
> +            <svg class="custom-input__icon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
А я в css через right и bottom сделал

2021-12-20 13:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-20 13:41 UTC, Khashiev commented on 07-lection5/04-input/index.html
> +            <svg class="custom-input__icon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
обернул custom-input__icon и custom-input__input в custom-input__control и спозиционировал иконку от-но враппера

2021-12-20 20:10 UTC, GSemikozov approved these changes

2021-12-20 20:11 UTC, merged