09 burger menu
js-tasks-ru/htmlcss-20211125_nxashiev pull request #24
Opened 2021-12-25 19:56 UTC by Khashiev

2021-12-25 19:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-26 11:00 UTC, GSemikozov requested changes

2021-12-26 11:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-26 11:56 UTC, Khashiev commented on 09-lection7/01-burger-menu/burger-menu.css
> +.modal__window {
сделал .burger-menu__inner

2021-12-26 11:59 UTC, Khashiev commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger__icon {
обернул все в блок menu. Исправил на .burger-menu__icon. Кнопке задал класс menu-button

2022-01-10 18:54 UTC, closed without merging