solution for 04-skeleton
js-tasks-ru/htmlcss-20211125_nxashiev pull request #8
Opened 2021-12-07 19:15 UTC by Khashiev

2021-12-07 19:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-08 13:15 UTC, GSemikozov requested changes

2021-12-08 13:15 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  border: 1px solid #acb5bd;
цвет все-таки желательно забрать из переменных

2021-12-08 13:15 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  background: #dde2e5;
и тут, и вообще везде :)

2021-12-08 13:15 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__rectangle_first {
модификаторы советовал бы именовать более семантично, например .skeleton__rectangle_short, _medium, _long, чтобы по классу было понятно что и как модифицируется

2021-12-08 13:15 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 172px;
здесь и ниже ширину лучше задавать в процентах

2021-12-13 15:13 UTC, GSemikozov requested changes

2021-12-13 15:13 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 500px;
это лишнее

2021-12-16 09:09 UTC, GSemikozov requested changes

2021-12-16 09:09 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  flex-basis: 80px; /**/
flex-basis сработал бы только если бы не было width: 64px; причем сработал бы неправильно (внешние отступы не участвуют в подсчете ширины, в том числе и базовой ширины)

2021-12-16 14:23 UTC, Khashiev commented on 04-lection2/02-skeleton/skeleton.css
> +  background: #dde2e5;
добавил через var

2021-12-16 14:23 UTC, Khashiev commented on 04-lection2/02-skeleton/skeleton.css
> +  border: 1px solid #acb5bd;
добавил через var

2021-12-16 14:24 UTC, Khashiev commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 172px;
избавился от жесткого фикса

2021-12-16 14:24 UTC, Khashiev commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 500px;
удалил

2021-12-16 14:24 UTC, Khashiev commented on 04-lection2/02-skeleton/skeleton.css
> +  flex-basis: 80px; /**/
удалил flex-basis

2021-12-16 20:34 UTC, GSemikozov approved these changes

2021-12-16 20:35 UTC, merged